        #miroktik upgrade script
        location ~ ^/ros6-upgrade.php {  deny all;  }

        location ~ ^/routeros/(NEWEST6\.stable|NEWESTa6\.stable|NEWEST6\.long-term|NEWESTa6\.long-term|NEWEST6\.upgrade|NEWESTa6\.upgrade)$ {
            include fastcgi_params;
            fastcgi_pass unix:/run/php/php-fpm.sock;
            fastcgi_param SCRIPT_FILENAME /mnt/mirror/ros6-upgrade.php;
            fastcgi_param QUERY_STRING    $query_string;
            fastcgi_param REQUEST_URI     $request_uri;
            # Отключаем chunked на исходящем ответе
            chunked_transfer_encoding off;
            # Буферизуем ответ PHP целиком, чтобы nginx мог посчитать Content-Length,
            # если PHP его не задал
            fastcgi_buffering on;
            # Не давать nginx добавлять/менять кодировки
            gzip off;
            proxy_set_header Accept-Encoding "";
        }
