# MikroTik upgrade script
location ~ ^/ros6-upgrade.php {  deny all;  }
location ~ ^/ros7-upgrade.php {  deny all;  }

location ~ ^/routeros/(NEWEST6\.stable|NEWESTa6\.stable|NEWEST6\.long-term|NEWESTa6\.long-term|NEWEST6\.upgrade|NEWESTa6\.upgrade)$ {
    include fastcgi_params;
    fastcgi_pass unix:/run/php/php-fpm.sock;
    fastcgi_param SCRIPT_FILENAME /mnt/mirror/ros6-upgrade.php;
    fastcgi_param QUERY_STRING    $query_string;
    fastcgi_param REQUEST_URI     $request_uri;

    # Disable chunked encoding on the outgoing response
    chunked_transfer_encoding off;

    # Buffer the entire PHP response so nginx can calculate Content-Length
    # if PHP did not provide it
    fastcgi_buffering on;

    # Prevent nginx from adding or modifying encodings
    gzip off;
    proxy_set_header Accept-Encoding "";
}

location ~ ^/routeros/(NEWEST7\.stable|NEWESTa7\.stable|NEWEST7\.long-term|NEWESTa7\.long-term|NEWEST7\.upgrade|NEWESTa7\.upgrade)$ {
    include fastcgi_params;
    fastcgi_pass unix:/run/php/php-fpm.sock;
    fastcgi_param SCRIPT_FILENAME /mnt/mirror/ros7-upgrade.php;
    fastcgi_param QUERY_STRING    $query_string;
    fastcgi_param REQUEST_URI     $request_uri;

    # Disable chunked encoding on the outgoing response
    chunked_transfer_encoding off;

    # Buffer the entire PHP response so nginx can calculate Content-Length
    # if PHP did not provide it
    fastcgi_buffering on;

    # Prevent nginx from adding or modifying encodings
    gzip off;
    proxy_set_header Accept-Encoding "";
}
